### PR TITLE
Adds toUppercase and replaceAll functions

### PR DESCRIPTION
**Pull request by CodeKrakken**
This update extends JMESPath functionality to include replaceAll and toUpper functions, along with tests.

The docs have also been updated with usage instructions for the new functions. There is some minor rephrasing of related functions in the interest of linguistic consistency.

### CODE REVIEW

**Review by lukestanley — CHANGES_REQUESTED** [review]
It would be good to have a description that describes all the changes you intend for the PR to introduce. There is more going on here than what the title suggests. It might seem obvious but it would be good for the tests to point out how the existing replace function works, for example (just a sketch): `"rulers:cat,cat".replace('cat','dog')=="rulers:dog,cat"`
By the way, I had to hide whitespace changes in the PR diff viewer, since there were indentation changes. Auto-formatted changes can really made understanding changes harder than need be. I'm glad this was easy to do in this PR view, but in the future, could we agree to keep indentation changes to a separate piece of work?
@CodeKrakken

**Comment by CodeKrakken** [comment]
No problem @lukestanley. I've added to the description and I agree about indentation - it's distracting amongst other changes. As for pointing out how the functions work, how about the below example?

`it('should replace one string instance within a larger string', () => {

    const data = { string: "test string before" };
    const expr1 = "replace(string, 'before', 'after')";
    const expected1 = "test string after";

    // "test string before".replace('before','after')=="test string after"

    expect(mappingUtility(data, expr1)).toBe(expected1);
  });`

**Comment by lukestanley** [comment]
Did you expect to commit a test for trim too? I didn't see it in the description.

> 
> ```
> it('should replace one string instance within a larger string', () => {
> 
>     const data = { string: "test string before" };
>     const expr1 = "replace(string, 'before', 'after')";
>     const expected1 = "test string after";
> 
>     // "test string before".replace('before','after')=="test string after"
> 
>     expect(mappingUtility(data, expr1)).toBe(expected1);
> });
> ```

No, I meant a test to make it obvious how .replace only replaces one item.
@CodeKrakken

**Comment by CodeKrakken** [comment]
I've removed the trim test - it's not relevant to this code change. I'll open an issue for increasing test coverage so we don't lose track of it.

I've updated my replace and replaceAll tests - they should be clearer now.

The numbers - do you mean `expr1` and `expected1`? I was just matching the existing style. I also don't see the need for them - shall we remove them? @lukestanley

**Comment by lukestanley** [comment]
Looks better now but I don't think you needed to remove the trim test, I was just pointing out that you had something committed, that you didn't have in the description.
@CodeKrakken

**Comment by lukestanley** [comment]
Ah I see! 'should parse Unix millisecond timestamp and return date string' and 'should parse Unix millisecond timestamp and return date string with format argument' both should not use numbers, but they wrongly do, it makes sense in other functions but not those.
@CodeKrakken

**Review by lukestanley — APPROVED** [review]
:+1: :sparkles:

**Pull request merged**
