### PR TITLE
Convert "Workflow" text to "Flow"

### PR DESCRIPTION
**Pull request by gsambrotta**
Wherever we have a text, label or documentation that use the refer to the Kendraio Flow, we want to call them `Flow`.
In this PR I substituted all the text that was calling the Flow in another way like:

- Workflow
- flow
- flow block

### CODE REVIEW

**Review by CodeKrakken — CHANGES_REQUESTED** [review]
Text looks fine - but we have a failing test - 
```
/kendraio-app/cypress/e2e/context_and_state.ts 
line 232 - 'should allow the disabling of the datagrid'```

**Comment by gsambrotta** [comment]
Ah thanks @CodeKrakken, locally all the tests were passing. I will check it again

**Review by lukestanley — APPROVED** [review]
:+1:

**Comment by lukestanley** [comment]
@gsambrotta 
For some reason this was merged into angular-16 instead of develop.
I feel bad I didn't catch it earlier.
But can you make a Pull Request for merging this into the right place?
I consider it blocking the Angular work.

**Pull request merged**
